services:
  shell:
    build:
      context: .
      dockerfile: projects/shell/Dockerfile
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - mfe1
      - mfe2
      - mfe3
    networks:
      - mfe-network

  mfe1:
    build:
      context: .
      dockerfile: projects/mfe1-dashboard/Dockerfile
    ports:
      - "4201:80"
    environment:
      - NODE_ENV=production
    networks:
      - mfe-network

  mfe2:
    build:
      context: .
      dockerfile: projects/mfe2-user-management/Dockerfile
    ports:
      - "4202:80"
    environment:
      - NODE_ENV=production
    networks:
      - mfe-network

  mfe3:
    build:
      context: .
      dockerfile: projects/mfe3-auth/Dockerfile
    ports:
      - "4203:80"
    environment:
      - NODE_ENV=production
    networks:
      - mfe-network

networks:
  mfe-network:
    driver: bridge

volumes:
  node_modules:
